### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by TheToto** [geoph9/hass-gshell-extension#11]
Hello,

Small suggestion for better integration with the gnome bar

![ha_white](https://user-images.githubusercontent.com/12860648/118378381-c56e5000-b5d3-11eb-8985-fa8a27f672b9.png)

![ha_before](https://user-images.githubusercontent.com/12860648/118378380-c4d5b980-b5d3-11eb-9472-cf922128a2ed.png)
![ha_after](https://user-images.githubusercontent.com/12860648/118378379-c4d5b980-b5d3-11eb-80f8-ac1e04562005.png)

**Comment by geoph9** [comment]
Hi,

Thanks for bringing this up. You are right, it does seem to integrate better with the gnome bar and the rest of the icons. I could add an extra entry in the settings for the users to pick the icon they want and make the white icon the default one.
