### ISSUE TITLE
Adding a scrollbar to the Togglables section

### ISSUE THREAD

**Issue by pixelsquared** [geoph9/hass-gshell-extension#13]
I have a lot of toggle entities in my home assistant and they get cut off at the bottom of my screen so I can't select the ones I want.
Could you add a scrollbar to that section?

**Comment by geoph9** [comment]
Hi! Thanks for the issue. 

- Could you maybe attach a screenshot of how it looks?
- If not, could you maybe share after how many entities are they starting to cut off? (Does that also mean that the `Preferences` option is completely hidden?)

**Comment by pixelsquared** [comment]
Cut off at the bottom:
![Screenshot from 2021-05-21 15-03-43](https://user-images.githubusercontent.com/10050016/119192473-d5f44f80-ba45-11eb-9007-b32bf3bd1a53.png)

Full window in gnome overview:
![Screenshot from 2021-05-21 15-03-56](https://user-images.githubusercontent.com/10050016/119192527-ed333d00-ba45-11eb-8300-afb67494d6ae.png)

One one item is cut off but I am going to add more devices in the future so it will be a bigger issue then.

**Comment by geoph9** [comment]
Thanks for sharing this! So, is your panel menu okay, though? Are all entities shown there without any issue?

**Comment by pixelsquared** [comment]
The panel menu is fine.

**Comment by geoph9** [comment]
I recreated the issue by adding some fake entities. #14 should solve it.
