### ISSUE TITLE
API call api/services/switch/toggle does not work for lights

### ISSUE THREAD

**Issue by baracoder** [geoph9/hass-gshell-extension#17]
For lights it should be `api/services/light/toggle`

**Comment by geoph9** [comment]
Thank you very much for bringing this up!

[This commit](https://github.com/geoph9/hass-gshell-extension/commit/36dc8f27a44e24b66e602df362b8d9daba553896) should fix the issue. I will test it myself next week and I will upload a new release if everything is okay. You can test this change by using the `build.sh` script with the `--latest` option.

Should also close #16

**Comment by geoph9** [comment]
I tested this and the fix seems to work. Thanks again for noticing it!
