### ISSUE TITLE
Also seems to work with gnome-shell version 41

### ISSUE THREAD

**Issue by gitmpr** [geoph9/hass-gshell-extension#23]
Changing the version number from 40 to 41 in the ~/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/metadata.json file was all that was needed to get this latest version 40 of the extension working on gnome 41.1 and allowing me to toggle on the extension in the extensions menu.
It seems to work fine with this newer version of gnome as well, so maybe it can be made compatible for both.

There is some version checking in build.sh that will currently only install the extension for gnome-shell versions 40.*

**Comment by geoph9** [comment]
Okay I just released tag `41` (for gnome 41) which can be found [here](https://github.com/geoph9/hass-gshell-extension/releases/tag/41). This means that `build.sh` will also work in Gnome 41, assuming that no major bugs are introduced by switching from gnome 40 to gnome 41 (I haven't made the change yet, so I haven't tested it personally).

Thanks for letting me know! The new version can also be downloaded [from e.g.o.](https://extensions.gnome.org/extension/4170/home-assistant-extension/) now (review is pending).
