### ISSUE TITLE
Gnome 41 related

### ISSUE THREAD

**Issue by geoph9** [geoph9/hass-gshell-extension#24]
These issues were in a review of the extension by @JustPerfection in [e.g.o.](https://extensions.gnome.org/extension/4170/home-assistant-extension/):

1. Also do this on disable:
hassExtension = null;

2. Lang is a deprecated module. Please remove it for the next version:
https://gjs.guide/extensions/review-guidelines/review-guidelines.html#general-advice
Learn how to remove Lang from your code:
https://gjs.guide/guides/gjs/legacy-class-syntax.html

**Comment by justperfection** [comment]
Also remove getSettings from utils.js. Use ExtensionUtils.getSettings() instead. and remove unnecessary lines [here](https://github.com/geoph9/hass-gshell-extension/blob/d535501ffa90e46c45fba35b35c5112580a8bf06/prefs.js#L25) and [here](https://github.com/geoph9/hass-gshell-extension/blob/d535501ffa90e46c45fba35b35c5112580a8bf06/settings.js#L27). When you have [this line](https://github.com/geoph9/hass-gshell-extension/blob/d535501ffa90e46c45fba35b35c5112580a8bf06/metadata.json#L8) in metadata.json file you don't need to send the parameter.

**Comment by geoph9** [comment]
Thank you for your help and pointers! These were all fixed in b318414
