### ISSUE TITLE
[Suggestion] More sensors

### ISSUE THREAD

**Issue by pkejval** [geoph9/hass-gshell-extension#25]
I think it would be nice to have ability to add more than temperature/hnmidity sensors to show at tray. Can it be extended add any number of custom sensors?

**Comment by geoph9** [comment]
Thanks for this suggestion!

Could you maybe provide an example of a custom sensor? I personally only have a DHT22 and so I am not aware of how Home Assistant reads other sensors.

I don't think it would be very hard to generalize to more sensors, so this is definitely doable.

**Comment by Bugscz** [comment]
By custom sensors I meant just more sensors. :) Other sensors in Home Assistant should work like your DHT22 - they provide state and unit of measurement.

**Comment by geoph9** [comment]
Hi, I just pushed a change in the `gnome40` branch. Could you maybe check it?

It should look like this:
![panel_sensors](https://user-images.githubusercontent.com/12800078/147285338-20559836-0ebe-4f4d-8510-23fa5b8a5880.png)
