### ISSUE TITLE
Add input_boolean switch detection

### ISSUE THREAD

**Issue by vijay-prema** [geoph9/hass-gshell-extension#28]
Thanks for this extension. One big improvement would be to add the `input_boolean` switch type to the `VALID_TOGGLABLES` detection. This made the extension much more useful to me as I use `input_boolean` as virtual software switches to run scripts to activate an IR blaster for turning on and off media center, AC and appliances.

Only 1 change needs to be made to support this:

**Change line 11 in utils.js from:**
```
const VALID_TOGGLABLES = ['switch.', 'light.', 'fan.'];
```
**to:**
```
const VALID_TOGGLABLES = ['switch.', 'light.', 'fan.', 'input_boolean.'];
```

**Comment by geoph9** [comment]
Hi! Sounds like a good idea, thanks for proposing this. Do you want to make a PR?

**Comment by vijay-prema** [comment]
ok let me try making the PR

**Comment by vijay-prema** [comment]
made PR https://github.com/geoph9/hass-gshell-extension/pull/29

**Comment by geoph9** [comment]
Thanks! PR #29 closes this.
