### ISSUE TITLE
Please upgrade to Gnome 42

### ISSUE THREAD

**Issue by ser** [geoph9/hass-gshell-extension#30]

**Comment by geoph9** [comment]
I am using Gnome 42 and I have no issues. Can you elaborate on your issue?

**Comment by ser** [comment]
No idea how it can work for you :)

https://github.com/geoph9/hass-gshell-extension/blob/02ed93c08bda5cdec01f3c746f9bfd84258f45d5/metadata.json#L5

**Comment by geoph9** [comment]
Ahhh my bad, I mixed the versions. I am not sure whether there have been many big changes when going from `41` to `42`. I'll try to test it on a VM whenever I have time.

**Comment by ser** [comment]
I have tested it for few days and I don't see any issues.

**Comment by geoph9** [comment]
Ok I added it but I will not officially release it until someone extensively tests it (I will probably test it in the near future).

For now, it can be installed by using the `build.sh` script and passing the `--latest` command.
