### ISSUE TITLE
GitHub version gets replaced by extension store version

### ISSUE THREAD

**Issue by julian-klode** [geoph9/hass-gshell-extension#31]
GNOME 42, cloned GitHub master into `~/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github`, on re-login, it gets "upgraded" from 1.5.2 to version 6 from the extension store, and duh, stops working.

**Comment by geoph9** [comment]
Right, I just submitted the `42` version on e.g.o. and it should "automatically upgrade" to the 42 version. To be honest I am not sure if this is the best choice (since I haven't tested the extension on Gnome 42), but I am a bit swamped right now so I just hope it will work.

**Comment by geoph9** [comment]
The new version is (`7`) is accepted in e.g.o. I am closing this issue.
