### ISSUE TITLE
GSettings key hass-enabled-sensor-ids not found in schema org.gnome.shell.extensions.hass-data

### ISSUE THREAD

**Issue by davefx** [geoph9/hass-gshell-extension#32]
When trying to activate extension in Gnome 42 in Ubuntu 22.04 I'm getting this error:

```
GSettings key hass-enabled-sensor-ids not found in schema org.gnome.shell.extensions.hass-data

**Comment by geoph9** [comment]
Hi,

Thanks for creating this issue! Last time I updated the extension on e.g.o. I accidentally uploaded a wrong schema. I submitted the corrected one for review and it should work after it gets accepted.

A quick way around it is to compile the current schema: `glib-compile-schemas $HOME/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github`. But this won't be needed after the update gets reviewed.

**Comment by geoph9** [comment]
I am closing this since the above fix worked on my tests. Feel free to re-open if the issue persists.
