### ISSUE TITLE
Uncleaned Information in Panel

### ISSUE THREAD

**Issue by cinatic** [geoph9/hass-gshell-extension#37]
Hi,

i noticed that on screen lock the stats get rendered but the previous not cleared. Not sure but i think it is because you need also to act and remove the panels on destroy manually with something like

```
this.menu.connect('destroy', this._destroyExtension.bind(this))
```

![Screenshot from 2022-06-13 09-09-51](https://user-images.githubusercontent.com/2721787/173298863-08557bd2-2cb3-4a0a-8c99-c37283269242.png)

**Comment by geoph9** [comment]
I wasn't using this feature and wasn't aware of this issue :/ If you have time to make a PR, I will review it quickly and merge it. Thanks for bringing it up!

**Comment by geoph9** [comment]
#38 Should supposedly solve this issue. I will leave this open, though, since I am not able to test it myself currently. Please let me know if this problem is solved for you.
