### ISSUE TITLE
Searchbar for Entities

### ISSUE THREAD

**Issue by masyfil** [geoph9/hass-gshell-extension#39]
I have a huge List of Entities. It would be great, if i can search through that list with a searchbar in the "Togglebles" section.

![likethis](https://user-images.githubusercontent.com/61693753/185738870-bbaa049b-4380-4d97-892b-defade0203d0.png)

**Comment by geoph9** [comment]
This was added in a previous version. The latest release (`master`, merged from #62 ) also includes that.
