### ISSUE TITLE
Please upgrade to Gnome 43

### ISSUE THREAD

**Issue by ser** [geoph9/hass-gshell-extension#41]
There is some roadblock:

```
Expected type string for argument 'property_name' but got type undefined
```

**Comment by geoph9** [comment]
Can you share the whole traceback? Where is this occurring?

**Comment by sylviiu** [comment]
Ran into same issue, just finished setting up home assistant solely for this extension haha

I was able to find this stack trace in journalctl:

`
Nov 02 04:16:59 sylviiu gnome-shell[1376]: JS ERROR: Extension hass-gshell@geoph9-on-github: Error: Expected type string for argument 'property_name' but got type undefined
                                           send_request@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/utils.js:46:13
                                           discoverSwitches@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/utils.js:69:28
                                           _getTogglableEntities@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:234:38
                                           rebuildTray@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:73:31
                                           _init@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:52:14
                                           HassMenu@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:29:4
                                           enable@/home/syl/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:437:21
`

**Comment by sylviiu** [comment]
Restarting my shell, I also discovered another error: `Requiring Soup but it has 2 versions available; use imports.gi.versions to pick one`

**Comment by geoph9** [comment]
Hi, thanks for posting these. Can you also share which OS you are using? I think the issue is that Gnome 43 is using Soup 3 while this extension uses the Soup 2 API. This complicates things a bit. I think the most viable solution would be to create a separate branch for Gnome 43 which will contain a different `utils.js` file (using Soup 3). 

[Here is a migration guide in case someone wants to implement this](https://gjs.guide/extensions/upgrading/gnome-shell-43.html#soup3). I will try to take a look at it myself within the next few days, but if you are willing to do it yourself I would be more than happy to help.

**Comment by sylviiu** [comment]
You're entirely right, I'm running Arch and my system has both soup 2 & 3 installed, which is why I'm getting the odd "multiple versions available" log as well.

I can definitely look into migrating and submitting a PR later on if you're fine with that.

**Comment by geoph9** [comment]
Sounds great, thanks! If you need any help let me know.

**Comment by horga83** [comment]
Thank you  for looking into the GNOME 43 issue, eagerly awaiting solution.
Cheers

**Comment by geoph9** [comment]
Hello again, I have just uploaded a possible fix for Gnome 43 (i.e. migration to libsoup 3). Can someone install it and report their findings? Running the following commands and restarting your shell should do the trick:

```bash
mkdir -p "$HOME"/.local/share/gnome-shell/extensions
git clone -b 43 https://github.com/geoph9/hass-gshell-extension.git "$HOME"/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github
```
