### ISSUE TITLE
Extension fails to start (Error: message is null)

### ISSUE THREAD

**Issue by Nosen92** [geoph9/hass-gshell-extension#51]
Using GNOME 43 on Fedora 37.
Installed using the recommended method.
The extension never starts.
In Extension Manager, it says "An error occurred while loading this extension".
The error is "message is null". Also the version number is 0 so the extension manager is flagging the extension to be updated.
Other extensions installed: Blur my shell, clipboard manager and gvfs-nfs.

**Comment by geoph9** [comment]
Hmm that's weird. By "recommended method" do you mean the [Direct Install](https://github.com/geoph9/hass-gshell-extension#direct-install) approach? Because if so, it shouldn't say that the version number is 0 (I don't think I've published any release with that version number). 

Can you share the output of `gnome-shell --version`?

**Comment by Nosen92** [comment]
Sure.
`GNOME Shell 43.2`

**Comment by geoph9** [comment]
And doing the following prints `"version": "0"`?

```
cat ~/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/metadata.json | grep version
```

**Comment by Nosen92** [comment]
Funny enough no:
```
    "shell-version" : [
    "version" : "12.3"
```

**Comment by Nosen92** [comment]
Here is a screenshot of extension manager:
![Screenshot from 2023-02-03 14-49-32](https://user-images.githubusercontent.com/59702101/216619572-9de65cc6-6c76-40b5-a24b-71bb4d4d42c9.png)

**Comment by geoph9** [comment]
This is very weird. I would suggest trying the following:

1. Delete it and re-install it.
2. Run `journalctl -f -o cat /usr/bin/gnome-shell` and turn the extension off and on again. Do you see any error related to the extension?

**Comment by geoph9** [comment]
For example this should work: `rm -rf ~/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/`. But, removing it from the extension manager should do the same.

**Comment by Nosen92** [comment]
Here is the output:
```
[nosen@fedora ~]$ journalctl -f -o cat /usr/bin/gnome-shell
soup_message_new_from_uri: assertion 'SOUP_URI_IS_VALID (uri)' failed
JS ERROR: Extension hass-gshell@geoph9-on-github: TypeError: message is null
_constructMessage@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/utils.js:32:5
send_request@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/utils.js:57:36
discoverSwitches@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/utils.js:81:28
_getTogglableEntities@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:232:38
rebuildTray@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:71:31
_init@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:50:14
ButtonBox@resource:///org/gnome/shell/ui/panelMenu.js:11:1
PanelMenuButton@resource:///org/gnome/shell/ui/panelMenu.js:97:4
HassMenu@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:27:4
enable@/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/extension.js:435:21
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:184:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:385:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:633:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:28:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:612:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:659:14
init@resource:///org/gnome/shell/ui/extensionSystem.js:57:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:309:22
start@resource:///org/gnome/shell/ui/main.js:186:5
@resource:///org/gnome/shell/ui/init.js:6:17

Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Failed to create color profile from colord profile: Error opening file /var/lib/gdm/.local/share/icc/edid-2c871cbd5442c66e59b266c1e0de1669.icc: Permission denied
GNOME Shell started at Fri Feb 03 2023 15:10:57 GMT+0100 (Central European Standard Time)
Registering session with GDM
Connection to xwayland lost
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Terminal/SearchProvider”
```

**Comment by Nosen92** [comment]
I'm going afk for a while now. Thanks for your help!

**Comment by Nosen92** [comment]
Also, apparently the extension manager updated the home assistant extension to version 15 after the reboot.

**Comment by geoph9** [comment]
No I meant the HASS URL you provided in the preferences. For example `http://0.0.0.0:8123/` or something like that.

**Comment by Nosen92** [comment]
Oh I can't enter it with the method provided in the readme because the extension never actually starts. I can enter it in the extension manager but that doesn't change the behavior.

**Comment by geoph9** [comment]
Hmm, these two are separate modules so the preferences should work. Can you execute `journalctl -o cat -f /usr/bin/gjs` and then try to press the settings button (e.g. from the extensions app you sent in the screenshot above). Do you see any error related to this extension?

**Comment by Nosen92** [comment]
No errors, this is the output as I opened the preferences and entered the URL and token (the token field said "Success!"):
```
[nosen@fedora ~]$ journalctl -o cat -f /usr/bin/gjs
JS LOG: Characters Application started
JS LOG: Characters Application exiting
JS LOG: Characters Application started
JS LOG: Characters Application exiting
JS LOG: Characters Application started
JS WARNING: [/home/nosen/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/utils.js 1]: Requiring Soup but it has 2 versions available; use imports.gi.versions to pick one
JS LOG: initializing Home Assistant Extension Preferences
JS LOG: Characters Application exiting
JS LOG: initializing Home Assistant Extension Preferences
```

**Comment by Nosen92** [comment]
Update: After a reboot, the extension updated to version 15 and appeared in the panel! Not sure what happened. Let me know if you want any more information, otherwise you can close the issue on my account. Thank you!

**Comment by geoph9** [comment]
Ok, so after you enter the URL and token, the extension can still not start? Do you get the same error message as you got before? I.e. the following?
```
soup_message_new_from_uri: assertion 'SOUP_URI_IS_VALID (uri)' failed
JS ERROR: Extension hass-gshell@geoph9-on-github: TypeError: message is null
```

You also seem to have two versions of Soup, and since the Gnome 43 uses the Soup3 version, you could set that explicitly by adding the following line on top of the `utils.js` file:
```
imports.gi.versions.Soup = "3";
```

**Comment by geoph9** [comment]
Good to know it worked! This behaviour should not have occurred, so this is a potential future issue. I will close this for now, but if you (or anyone else) encounter anything similar, feel free to reopen it.
