### ISSUE TITLE
Only one sensor selected, but displayed 3 times

### ISSUE THREAD

**Issue by ni-ka** [geoph9/hass-gshell-extension#54]
I have only activated one sensor to display in the panel (a pm25 from a pollution detector). However it is displayed 3 times - I have 3 toggle switches selected, coincidence?

![Screenshot from 2023-02-25 19-05-03](https://user-images.githubusercontent.com/1225776/221375225-9bb54522-4cdd-4fb3-9bc5-f3b5653458bb.png)

**Comment by geoph9** [comment]
Are they three separate buttons or a single entity (e.g. if you hover at one of them, do all of them get selected of not)?

**Comment by geoph9** [comment]
This issue was probably caused by my refresh function. @brenard 's updates on #62  should have fixed this.
