### ISSUE TITLE
Access Token is not saved

### ISSUE THREAD

**Issue by FilipLaurentiu** [geoph9/hass-gshell-extension#55]
I added the URL in the General Settings, click "Add", it's ok.
I add the access token that I generate it from HA, click "Add", a message with "Success!" show up.
If I close and open it again my access token disappear and the connection is not working, of course

**Comment by Bulgus** [comment]
Same issue

**Comment by geoph9** [comment]
The access token is sensitive information and is hence hidden after being submitted (it is never saved in plain form).

Have you tried restarting the extension (log-out and re-login)? Or maybe your access token has expired? Or maybe your HASS instance does not allow HTTP requests?

I don't think this is related to the extension, but do let me know if the issue persists after you've tried answering the above questions.
