### ISSUE TITLE
Bug on master: Cannot check or uncheck togglables or panel sensors

### ISSUE THREAD

**Issue by MexHigh** [geoph9/hass-gshell-extension#65]
While trying to implement PR #64 (Issue #63) I encountered the issue that no Togglables or Panel Sensors can be checked or unchecked in the settings panel. The tick can be set while the window is open, but the content of the schema keys `hass-enabled-sensor-ids` and `hass-enabled-entities` don't change. When closing the settings pages, the ticks are reset like they were before.

Tested on commit hash 6c31b24e94ed174456ed5582d50fe04abb3284ea

This issue does not occur in the Gnome Extension Store version.

**Comment by geoph9** [comment]
Thanks! I actually also noticed that during my recent testing and PR #62 has solved it. I will keep this issue open until #62 is merged. There is no need to work on a fix for it now.

**Comment by MexHigh** [comment]
#62 is fixed and this works again, closing
