### ISSUE TITLE
Token does not seems to be saved

### ISSUE THREAD

**Issue by ps1x** [geoph9/hass-gshell-extension#67]
I have fedora 38 with gnome 44, it seems to me that token is not saved at all, Home assistant tells me unsuccessfull login attempt after i save token, also when i close settings and open it again token field is empty. Where can i get more info for you?

**Comment by geoph9** [comment]
What hass-gshell-extension version are you using?

**Comment by ps1x** [comment]
Im not really sure, as there is no info about version anywhere, but i use it from gnome-extensions website: https://extensions.gnome.org/extension/4170/home-assistant-extension/

**Comment by geoph9** [comment]
That's weird, I haven't encountered that before. Could you try to install from source (see [here](https://github.com/geoph9/hass-gshell-extension/issues/67#issuecomment-1663823257) for instructions) and report whether the issue still persists?

**Comment by ps1x** [comment]
> That's weird, I haven't encountered that before. Could you try to install from source (see [here](https://github.com/geoph9/hass-gshell-extension/issues/67#issuecomment-1663823257) for instructions) and report whether the issue still persists?

That worked, now token saves and everything works as intended, thank you!
