### ISSUE TITLE
Gnome 45 support?

### ISSUE THREAD

**Issue by infeeeee** [geoph9/hass-gshell-extension#68]
Version 45 just landed. There is some docs how to update:

https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by liamlah** [comment]
Thanks. I came here since I got an error after upgrading. The sensors on my status bar still work and update, but I get this error if I try to open the extension's preferences. If you want me to remove this and create a separate bug report, let me know.

The settings of extension hass-gshell@geoph9-on-github had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/liam/.local/share/gnome-shell/extensions/hass-gshell@geoph9-on-github/prefs.js:3:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by geoph9** [comment]
Yes, Gnome 45 changed the import declarations so this makes sense. I'll first need to merge #64 and then I'll make the necessary changes for the 45 upgrade.

Since this extension is pretty basic, I don't think any radical changes will need to be made so this shouldn't take long.

**Comment by horga83** [comment]
Any word about when a 45 version will be available?
Miss this one.

**Comment by geoph9** [comment]
Hi @horga83, thanks for the reminder, I'll take a look at it over the weekend!

**Comment by geoph9** [comment]
Hello again, I am reopening this since #70 is now ready to be merged and I would appreciate it if someone could test the changes (i.e. clone the `gnome45` branch and install the app as shown in the README).

**Comment by horga83** [comment]
This seems to work well, thanks you. no issues found so far.

**Comment by MexHigh** [comment]
Also tested it, works for me, too.
