### ISSUE TITLE
Remove duplicate Temperature & Humidity ID from  General Settings.

### ISSUE THREAD

**Issue by czar** [geoph9/hass-gshell-extension#69]
I accidentally clicked [Add] multiplule times after entering my Temperature ID and Humidity ID into Settings > general > Temperature/Humidity options.    Now the temp shows up multiple times (in the tray/bar.)  How can one remove duplicates?  Only button i'm finding is ADD, no modify or remove.  Thanks.

**Comment by geoph9** [comment]
That's an interesting bug, could you share your system details (hass version, OS, gnome version)?

To remove the duplicates I would advise you to uninstall the extension, delete its entry from dconf (e.g. through dconf-editor), and then re-install. That should work, but let me know if it doesn't!

**Comment by czar** [comment]
> That's an interesting bug, could you share your system details (hass version, OS, gnome version)?
Ubuntu 22.04, Gnome 42.9.  Hass 2023.11.3
 
> To remove the duplicates I would advise you to uninstall the extension, delete its entry from dconf (e.g. through dconf-editor), and then re-install. That should work, but let me know if it doesn't!
I reinstalled the extension and rebooted, this seems to work!  thanks.
