### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by NekoPavel** [geoph9/hass-gshell-extension#74]
Hi,
Gnome 46 just released a few days ago.
Found this on how to update: [https://gjs.guide/extensions/upgrading/gnome-shell-46.html](https://gjs.guide/extensions/upgrading/gnome-shell-46.html)
Appreciate your extension!

**Comment by geoph9** [comment]
Thanks @NekoPavel! I'll take a look at it this week.

**Comment by infeeeee** [comment]
For me it's working as expected, just the version number should be bumped, with version validation disabled this extension works perfectly, can't see anything in the logs.

**Comment by geoph9** [comment]
Thanks for checking this @infeeeee, I'll update the release shortly!

**Comment by geoph9** [comment]
Gnome 46 release has been published! I've also submitted the release on e.g.o. and it should be approved within the week. I am closing this issue for now...
