### ISSUE TITLE
Upload v47 to extensions.gnome.org

### ISSUE THREAD

**Issue by wrenix** [geoph9/hass-gshell-extension#81]
On https://extensions.gnome.org/extension/4170/home-assistant-extension/ is the "newest version" still 46 but we have 47 already.

**Comment by geoph9** [comment]
Ah right, thanks @wrenix . I'll upload it ASAP.

**Comment by Doooooo0o** [comment]
> On https://extensions.gnome.org/extension/4170/home-assistant-extension/ is the newest version still 46 but we have 47 already.

+1 :smiley:

**Comment by geoph9** [comment]
Done, v47 is currently under review on e.g.o! Thanks guys and sorry for taking that long!
